apiVersion: v1
kind: Network
baseDomain: ocp.local
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: cluster # Cluster name
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/16
      hostPrefix: 23
  machineNetwork:
    - cidr: 10.1.10.0/24
  networkType: OVNKubernetes
  serviceNetwork:
    - 10.96.0.0/16
